// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgrammersDiary.Data.Context;

#nullable disable

namespace ProgrammersDiary.Data.SqlServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220608171459_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProgrammersDiary.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LinguagemId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LinguagemId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ProgrammersDiary.Domain.Entities.Linguagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LabelLinguagem")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Linguagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LabelLinguagem = "js",
                            Nome = "babel"
                        },
                        new
                        {
                            Id = 2,
                            LabelLinguagem = "css",
                            Nome = "css"
                        },
                        new
                        {
                            Id = 3,
                            LabelLinguagem = "json",
                            Nome = "babel"
                        },
                        new
                        {
                            Id = 4,
                            LabelLinguagem = "ts",
                            Nome = "typescript"
                        },
                        new
                        {
                            Id = 5,
                            LabelLinguagem = "scss",
                            Nome = "scss"
                        },
                        new
                        {
                            Id = 6,
                            LabelLinguagem = "less",
                            Nome = "less"
                        },
                        new
                        {
                            Id = 7,
                            LabelLinguagem = "markdown",
                            Nome = "markdown"
                        },
                        new
                        {
                            Id = 8,
                            LabelLinguagem = "html",
                            Nome = "html"
                        },
                        new
                        {
                            Id = 9,
                            LabelLinguagem = "php",
                            Nome = "php"
                        },
                        new
                        {
                            Id = 10,
                            LabelLinguagem = "xml",
                            Nome = "xml"
                        });
                });

            modelBuilder.Entity("ProgrammersDiary.Domain.Entities.Card", b =>
                {
                    b.HasOne("ProgrammersDiary.Domain.Entities.Linguagem", "Linguagem")
                        .WithMany("Cards")
                        .HasForeignKey("LinguagemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Linguagem");
                });

            modelBuilder.Entity("ProgrammersDiary.Domain.Entities.Linguagem", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
